sudo: required
services:
  - docker

before_install:
  - docker build -t shdkapoor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shdkapoor/react-test npm run test

after_success:
  - docker build -t shdkapoor/multi-client ./client
  - docker build -t shdkapoor/multi-nginx ./nginx
  - docker build -t shdkapoor/multi-server ./server
  - docker build -t shdkapoor/multi-worker ./worker

  #log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # TAke those images and push them to docker hub
  - docker push shdkapoor/multi-client
  - docker push shdkapoor/multi-nginx
  - docker push shdkapoor/multi-server
  - docker push shdkapoor/multi-worker

